#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 12345
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: chat_app_prod

#Server
SERVER_PORT: 9021
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: vkychatapp@gmail.com
EMAIL_PASSWORD: amwzzalzhphcoiqc
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

AUTH_PORT: 9001
MAIL_PORT: 9021
USER_PORT: 9011