#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 12345
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: chat_app_dev
RABBITMQ_HOST: localhost
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: veysel
RABBITMQ_PASSWORD: 123

#Server
SERVER_PORT: 9010
ACTIVE_PROFILE: dev

AUTH_PORT: 9000
MAIL_PORT: 9020
USER_PORT: 9010
